version: '3.9'

services:
  rosalindfranklin_postgres:
    image: postgres:15
    container_name: rosalindfranklin_postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rosalindfranklin_net


volumes:
  postgres-data:

networks:
  rosalindfranklin_net:
